force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stack__c/User_Stack__c.object-meta.xml
<CustomObject>
    <description>The Stack to User assignment Object.</description>
    <label>User Stack</label>
    <nameField>
        <displayFormat>UseS-{000000}</displayFormat>
        <label>User Stack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stack__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>User Stacks</relationshipLabel>
    <relationshipName>User_Stacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Stack__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignStacksPageController.cls
public class AssignStacksPageController {

	@auraenabled
    public static List<contact> AssociateSearch(String AName){
        AName = String.isBlank(AName) ? '%%' : AName + '%';
        list<contact> Associates = [SELECT Id, Name FROM Contact WHERE Name like :AName];
        return Associates;
    }
    
    @AuraEnabled
    public static List<Stack__c> StackSearch(String SName){
        SName = String.isBlank(SName) ? '%%' : SName + '%';
        List<Stack__c> Stacks = [SELECT Id, Name FROM Stack__c WHERE Name like :SName];
        return Stacks;
    }
    
    @AuraEnabled
    public static void SetUserStack(String sID, String aID){
        User assignUser = [SELECT id FROM User WHERE ContactId = :aID LIMIT 1];
        User_Stack__c us = new User_Stack__c();
        us.User__c = assignUser.id;
        us.Stack__c = sID;
        insert us;
    }
}