force-app/main/default/objects/Primary_Tech__c/Primary_Tech__c.object-meta.xml
<CustomObject>
    <description>The overview tech  that can be associated to multiple stacks that will multiple sub techs which will inform which challenges belong</description>
    <label>Primary Tech</label>
    <nameField>
        <label>Primary Tech Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Techs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stack_Tech__c/Stack_Tech__c.object-meta.xml
<CustomObject>
    <description>The Primary Tech to Stack assignment junction object.</description>
    <label>Stack Tech</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Stack Tech Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stack Techs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stack_Tech__c/fields/Primary_Tech__c.field-meta.xml
<CustomField>
    <fullName>Primary_Tech__c</fullName>
    <label>Primary Tech</label>
    <referenceTo>Primary_Tech__c</referenceTo>
    <relationshipLabel>Stack Techs</relationshipLabel>
    <relationshipName>Stack_Techs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stack_Tech__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>Stack Techs</relationshipLabel>
    <relationshipName>Stack_Techs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Stack__c/User_Stack__c.object-meta.xml
<CustomObject>
    <description>The Stack to User assignment Object.</description>
    <label>User Stack</label>
    <nameField>
        <displayFormat>UseS-{000000}</displayFormat>
        <label>User Stack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stack__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>User Stacks</relationshipLabel>
    <relationshipName>User_Stacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Stack__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/techDisplayController.cls
public class techDisplayController {
    @AuraEnabled
    public static List<Primary_Tech__c> getTech(){
        Id Userid = userInfo.getUserId();
        List<User_Stack__c> sl = [SELECT Name, Stack__c FROM User_Stack__c WHERE User__c=:UserId];
        List<id> idList = new List<Id>();
        for(User_Stack__c su:sl){
            idList.add(su.stack__c);
        }
        List<Stack__c> stacks = [SELECT Name,Id FROM Stack__c WHERE Id in :idList];
        List<String> ptSet= new List<String>();
        List<Primary_Tech__c> ptSetTwo= new List<Primary_Tech__c>();
        for(Stack_Tech__c s: [SELECT Name,Id,Primary_Tech__c,Stack__c FROM Stack_Tech__c]){
            for(Stack__c st: stacks){
                if(st.id == s.Stack__c && !ptSet.contains(s.Primary_Tech__c)){
                    ptSet.add(s.Primary_Tech__c);
                }
            }
        }
        integer x = 0;
        for(Primary_Tech__c p:[SELECT Name, Id FROM Primary_Tech__c]){
            if(ptSet.contains(p.id)){
                ptSetTwo.add(p);
            }
        }
        system.debug(ptSetTwo);
        return ptSetTwo;
    }
}