force-app/main/default/objects/Account/recordTypes/Batch.recordType-meta.xml
<RecordType>
    <fullName>Batch</fullName>
    <active>true</active>
    <label>Batch</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Batch_Client__c/Batch_Client__c.object-meta.xml
<CustomObject>
    <label>Batch Client</label>
    <nameField>
        <label>Batch Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Client__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch Clients</relationshipLabel>
    <relationshipName>Batch_Clients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Client__c/fields/Interested_Client__c.field-meta.xml
<CustomField>
    <fullName>Interested_Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interested Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch Clients (Interested Client)</relationshipLabel>
    <relationshipName>Batch_Clients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchClientlistContoller.cls
public with sharing class BatchClientlistContoller {
     @AuraEnabled
     public static PageWrapper LoadData(Decimal pageNumber ,Integer recordToDisply)
     {    Integer pageSize = recordToDisply; //Determine number of records to display based on input value
          Integer offset = ((Integer)pageNumber - 1) * pageSize; //deals with pagination
          PageWrapper obj =  new PageWrapper();
          // Get btach client Rec type
          obj.BatchList=[SELECT name FROM Account WHERE RecordType.DeveloperName ='Batch'];
          obj.BatchClient = [SELECT Name,Interested_Client__r.Name,Batch__r.Name FROM Batch_Client__c LIMIT :recordToDisply OFFSET :offset];
          obj.page = (Integer) pageNumber;
          obj.total = [SELECT count() FROM Batch_Client__c];
          return obj;
     }
     
    @AuraEnabled
    public static PageWrapper fetchBatchClient(Decimal pageNumber ,Integer recordToDisply,string picklistV) {
         Integer pageSize = recordToDisply;
         Integer offset = ((Integer)pageNumber - 1) * pageSize;
       
       // create a instance of wrapper class.
       PageWrapper obj =  new PageWrapper();
       // set the pageSize,Page(Number), total records and accounts List(using OFFSET)   
           obj.pageSize = pageSize;
           if(picklistV=='ALL')
           {
               obj.BatchClient = [SELECT Name,Interested_Client__r.Name,Batch__r.Name FROM Batch_Client__c LIMIT :recordToDisply OFFSET :offset];
           }
     
           else{
             //other Soql to get data from pick list
             obj.BatchClient=[SELECT Name,Interested_Client__r.Name,Batch__r.Name FROM Batch_Client__c WHERE Batch__r.Name=:picklistV LIMIT :recordToDisply OFFSET :offset];
           }
           obj.page = (Integer) pageNumber;
           obj.total = [SELECT count() FROM Batch_Client__c];
       // return the wrapper class instance .
           return obj;
        }

      
    // create a wrapper class with @AuraEnabled Properties    
    public class PageWrapper {
       @AuraEnabled public Integer pageSize {get;set;}//5, 10, or 20
       @AuraEnabled public Integer page {get;set;} //page you're on
       @AuraEnabled public Integer total {get;set;} //total number of pages
       @AuraEnabled public List<Batch_Client__c> BatchClient {get;set;}//The records to be displayed
       @AuraEnabled public List<Account> BatchList {get;set;}//used for populating picklist with values 
      }
}