force-app/main/default/objects/Account/recordTypes/Batch.recordType-meta.xml
<RecordType>
    <fullName>Batch</fullName>
    <active>true</active>
    <label>Batch</label>
</RecordType>

miaCreateMeetingComp/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Batch_Client__c/Batch_Client__c.object-meta.xml
<CustomObject>
    <label>Batch Client</label>
    <nameField>
        <label>Batch Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Client__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch Clients</relationshipLabel>
    <relationshipName>Batch_Clients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Client__c/fields/Interested_Client__c.field-meta.xml
<CustomField>
    <fullName>Interested_Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interested Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch Clients (Interested Client)</relationshipLabel>
    <relationshipName>Batch_Clients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

interview-board-administration/main/default/classes/BatchClientCreationController.cls
public class BatchClientCreationController {

    //Get all account records with the batch recordtype id
    @AuraEnabled
    public static List<Account> getBatchAccounts(){
        //In Dev branch, batch record type id should be => 0125w000001PYxsAAG
        RecordType batch = [Select name, Id from RecordType where sObjectType='Account' and Name = 'Batch' Limit 1];
        String batchRecordTypeId = batch.id;

        Id batchTypeId =
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Batch').getRecordTypeId();

        return [SELECT Name, Id FROM Account WHERE RecordTypeId =: batchTypeId];  
    }

    //Get all account records with the client recordtype id
    @AuraEnabled
    public static List<Account> getClientAccounts(){
        //In Dev branch, client record type id should be => 0125w000001PYxtAAG
        RecordType client = [Select name, Id from RecordType where sObjectType='Account' and Name = 'Client' Limit 1];
        String clientRecordTypeId = client.id;
        
        Id clientTypeId =
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();

        return [SELECT Name, Id FROM Account WHERE RecordTypeId =: clientTypeId];   
    }
    
    //create a batch client record based on user input.
    @AuraEnabled
    public static void createBatchClientObj(String batchId, String clientId, String name){
  
        Batch_Client__c batchClient = new Batch_Client__c();
        batchClient.Name = name;
        batchClient.Interested_Client__c =clientId;
        batchClient.Batch__c =batchId;
        System.debug('batchClient => ' + batchClient);
        insert batchClient;
    }

}