force-app/main/default/objects/Account/recordTypes/Batch.recordType-meta.xml
<RecordType>
    <fullName>Batch</fullName>
    <active>true</active>
    <label>Batch</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Batch_Client__c/Batch_Client__c.object-meta.xml
<CustomObject>
    <label>Batch Client</label>
    <nameField>
        <label>Batch Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Client__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch Clients</relationshipLabel>
    <relationshipName>Batch_Clients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Client__c/fields/Interested_Client__c.field-meta.xml
<CustomField>
    <fullName>Interested_Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interested Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch Clients (Interested Client)</relationshipLabel>
    <relationshipName>Batch_Clients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchClientCreationTest.cls
@isTest
public without sharing class BatchClientCreationTest {

   @TestSetup
    public static void createRecords(){
        
        //create the account records with appropriate record type for both
        //'0125w000000LYXSAA4' client recordtype id
        //'0125w000000LYXTAA4' batch recordtype id
        
        Id batchTypeId =
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Batch').getRecordTypeId();

        Account alpha = new Account();
        alpha.Name = 'Johnson';
        alpha.RecordTypeId = batchTypeId;

        Id clientTypeId =
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        
        Account beta = new Account();
		beta.Name = 'Anderson';
        beta.RecordTypeId = clientTypeId;

        //insert records
        insert alpha;
        insert beta;
    }

    @isTest
    public static void testMethod1(){
     List<Account> client = BatchClientCreationController.getBatchAccounts();
        System.assertEquals('Johnson', client[0].Name);
    }
    
    
    @isTest
    public static void testMethod2(){
     List<Account> client = BatchClientCreationController.getClientAccounts();
        System.assertEquals('Anderson', client[0].Name);
    }
    
    
      
    @isTest
    public static void testMethod3(){
        
        
        Account cl = [Select ID, name From Account where Name ='Anderson' Limit 1];
        Account ba = [Select ID, name From Account where Name ='Johnson' Limit 1];
		String clId = cl.id;
        String baId = ba.id;

    	BatchClientCreationController.createBatchClientObj(cl.id, ba.id,'supercalifragilisticexpialidocious');
        
         Batch_Client__c  charlie = [Select Name, Id, Batch__c, Interested_Client__c From  Batch_Client__c  where name ='supercalifragilisticexpialidocious' Limit 1];
         System.assertEquals(clId,   charlie.Batch__c);
         System.assertEquals(baId,  charlie.Interested_Client__c);
    }
    
    
}