force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Batch_Client__c/Batch_Client__c.object-meta.xml
<CustomObject>
    <label>Batch Client</label>
    <nameField>
        <label>Batch Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/Interview_Question__c.object-meta.xml
<CustomObject>
    <label>Interview Question</label>
    <nameField>
        <label>Interview Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataCreationTest.cls
@isTest
public with sharing class TestDataCreationTest {
    
    @isTest
    public static void resetTest()
    {
        Test.startTest();
        TestDataCreation.reset();
        Test.stopTest();

        List<List<sObject>> objs = new List<List<sObject>>();
        objs.add([SELECT Id, (SELECT Id FROM Contacts), Account.RecordType.Name FROM Account]);
        objs.add([SELECT Id FROM Batch_Client__c]);
        objs.add([SELECT Id FROM Meeting__c]);
        objs.add([SELECT Id FROM Meeting_Participant__c]);
        objs.add([SELECT Id FROM Interview_Question__c]);

        System.assertEquals(15, objs.get(0).size());
        for(Account a : (List<Account>)objs.get(0))
        {
            if(a.RecordType.Name == 'Client')
            {
                System.assert(1 <= a.Contacts.size());
                System.assert(3 >= a.Contacts.size());
            }
            else
            {
                System.assert(10 <= a.Contacts.size());
                System.assert(20 >= a.Contacts.size());
            }
        }

    }
}