force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Selected__c.field-meta.xml
<CustomField>
    <fullName>Date_Selected__c</fullName>
    <label>Date Selected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/classes/findSelectedAssociates.cls
public with sharing class findSelectedAssociates {

    private final List<Contact> associates;

    public findSelectedAssociates() {
        //Edit later with recordType = associate
        //associates = [SELECT Name, Email FROM User WHERE Date_Selected__c >= :(system.now()).date()-7];
        List<RecordType> RecordTypeList = [SELECT Id, SObjectType, Name FROM RecordType WHERE ( (SObjectType='Contact' 
                                                                                                AND Name='Associate') 
                                                                                                OR (SObjectType='Account' AND Name='Client') ) LIMIT 2];

        RecordType associateRecordType;
        RecordType clientRecordType;

        if (RecordTypeList[0].Name=='Associate'){
            associateRecordType = RecordTypeList[0];
            clientRecordType = RecordTypeList[1];
        } else {
            associateRecordType = RecordTypeList[1];
            clientRecordType = RecordTypeList[0];
        }
        associates = [SELECT Name, Email, Client__r.Name FROM Contact WHERE (RecordTypeId=:associateRecordType.Id 
                                                                            AND Date_Selected__c>= :(system.now()).date()-7 )];
    }

    public List<Contact> getSelectedAssociates(){
        return associates;
    }
}