force-app/main/default/objects/Account/fields/BatchId__c.field-meta.xml
<CustomField>
    <fullName>BatchId__c</fullName>
    <label>Batch Id</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Batch.recordType-meta.xml
<RecordType>
    <fullName>Batch</fullName>
    <active>true</active>
    <label>Batch</label>
</RecordType>

force-app/main/default/objects/Challenge__c/Challenge__c.object-meta.xml
<CustomObject>
    <description>The specific task that a User would need to complete to get credit to be used for their overall score.</description>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Challenge__c/fields/CaliberID__c.field-meta.xml
<CustomField>
    <fullName>CaliberID__c</fullName>
    <description>This is the external CaliberID.</description>
    <externalId>true</externalId>
    <label>CaliberID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Challenge__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the tech the challenge is about.</description>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>Challenges</relationshipLabel>
    <relationshipName>Challenges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Completion__c/Completion__c.object-meta.xml
<CustomObject>
    <description>The Junction object for Challenges and User that is used to keep a record of completed challenges. Records of this object should be created when User is assigned a Stack.</description>
    <label>Completion</label>
    <nameField>
        <displayFormat>Comp-{0000000}</displayFormat>
        <label>Completion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Completion__c/fields/CaliberID__c.field-meta.xml
<CustomField>
    <fullName>CaliberID__c</fullName>
    <externalId>true</externalId>
    <label>CaliberID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Completion__c/fields/Challenge__c.field-meta.xml
<CustomField>
    <fullName>Challenge__c</fullName>
    <label>Challenge</label>
    <referenceTo>Challenge__c</referenceTo>
    <relationshipLabel>Completions</relationshipLabel>
    <relationshipName>Completions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact/fields/BatchId__c.field-meta.xml
<CustomField>
    <fullName>BatchId__c</fullName>
    <label>BatchId</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SalesforceId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceId__c</fullName>
    <label>SalesforceId</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

interview-board-administration/main/default/classes/SyncUtitlityTest.cls
/*
    Test class to test SyncUtilityClass.cls methods
*/
@isTest
private class SyncUtitlityTest {
    @TestSetup
    static void makeData(){
        Account[] batches = new Account[]{};
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Batch').getRecordTypeId();
        for(Integer i=0; i<5; i++) {
            batches.add(new Account(name='Test' + i, batchId__c='TR-123' + i, recordTypeId=recordTypeId) );
        }
        insert batches;
    }

    @isTest
    private static void testGetData() {
        SyncUtilityClass SUC = new SyncUtilityClass();
        Test.setMock(HttpCalloutMock.class, new SyncCalloutMock());
        
        Test.startTest();
        SUC.getData();
        Test.stopTest();
        
        //System.debug( 'size: '+ contacts.size() + 'contacts: ' + contacts );
        System.assertEquals(2, SUC.externalAssociates.size());
        System.assertEquals(2, SUC.externalBatches.size());
    }

    //method to test compareContacts() in SyncUtilityClass
    @isTest
    private static void testCompareContacts(){
        SyncUtilityClass SUC = new SyncUtilityClass();
        //Generate test data 
        List<Contact[]> listOfContactLists = new List<Contact[]>();
        Contact[] contactList1 = new Contact[]{
            new Contact(
                lastName='Test1',
                SalesforceId__c='SF-1234',
                email='Someemail1@email.com'
            ),
            new Contact(
                lastName='Test2',
                SalesforceId__c='SF-2234',
                email='Someemail2@email.com'
            ),
            new Contact(
                lastName='Test3',
                SalesforceId__c='SF-3234',
                email='Someemail3@email.com'
            )
        };
        //Added twice to check for duplicate values
        listOfContactLists.add(contactList1);
        listOfContactLists.add(contactList1);
        //System.debug('List of lists: ' + ListOfContactLists);

        Contact[] contactList2 = new Contact[]{
            new Contact(
                lastName='Test1',
                SalesforceId__c='SF-1234',
                email='Someemail1@email.com'
            ),
            new Contact(
                lastName='Test2',
                SalesforceId__c='SF-2234',
                email='Someemail2@email.com'
            ),
            new Contact(
                lastName='Test4',
                SalesforceId__c='SF-4234',
                email='Someemail4@email.com'
            )  
        };
		//System.debug(contactList2);
        
        //Call the method
        List<Contact> result = SUC.compareContacts(listOfContactLists, contactList2);

        System.debug(result);
        //Check the result list, should contain only 1 instance of Test3
        System.assertEquals(1, result.size());
        System.assertEquals('SF-3234', result[0].SalesforceId__c);
        System.assertEquals('Someemail3@email.com', result[0].email);
    }

    @isTest
    private static void testCompareBatches(){
        SyncUtilityClass SUC = new SyncUtilityClass();
        //Generate test data
        Account[] accountList1 = new Account[]{
            new Account(
                Name='TestAccount1',
                BatchId__c='BC-1234'
            ),
            new Account(
                Name='TestAccount2',
                BatchId__c='BC-1234'
            ),
            new Account(
                Name='TestAccount3',
                BatchId__c='BC-1235'
            )
        };
        Account[] accountList2 = new Account[]{
            new Account(
                Name='TestAccount1',
                BatchId__c='BC-1234'
            ),
            new Account(
                Name='TestAccount2',
                BatchId__c='BC-1234'
            ),
            new Account(
                Name='TestAccount4',
                BatchId__c='BC-1236'
            )
        };

        //Run method
        Account[] result = SUC.compareBatches(accountList1, accountList2);

        //Test resulting List
        System.assertEquals(1, result.size());
        System.assertEquals('TestAccount3', result[0].Name);
        System.assertEquals('BC-1235', result[0].BatchId__c);
    }

    @isTest
    private static void testMatchAssociateToBatch(){
        SyncUtilityClass SUC = new SyncUtilityClass();

        //Generate test data
        Contact[] contactList = new Contact[]{
            new Contact(
                lastName='Test1',
                SalesforceId__c='SF-1234',
                email='Someemail1@email.com',
                batchId__c='TR-1231'
            ),
            new Contact(
                lastName='Test2',
                SalesforceId__c='SF-2234',
                email='Someemail2@email.com',
                batchId__c='TR-1231'
            ),
            new Contact(
                lastName='Test4',
                SalesforceId__c='SF-4234',
                email='Someemail4@email.com',
                batchId__c='TR-1238'
            )
        };
		insert contactList;
        
        System.debug('Contact List' + contactList);
        test.startTest();
            SUC.matchAssociateToBatch(contactList);
        test.stopTest();
        
        ID AccountId = [SELECT ID FROM Account WHERE BatchId__c = 'TR-1231'].id;
        
        System.assertEquals(AccountId, contactList[0].AccountId);
        System.assertEquals(AccountId, contactList[1].AccountId);
        System.assertEquals(null, contactList[2].AccountId);
    }

    //Method to test the updateDatabases() method
    @isTest 
    private static void testUpdateDatabase(){
        SyncUtilityClass SUC = new SyncUtilityClass();
        Test.setMock(HttpCalloutMock.class, new SyncCalloutMock());

        List<sObject> toInsert = new List<sObject>();
        Challenge__c achallenge = new Challenge__c(Name='toupdate',CaliberID__c='1658');
        Stack__c astack = new Stack__c(Name='.NET',CaliberID__c='8');
        toInsert.add(achallenge); toInsert.add(astack);
        insert toInsert;
        Completion__c acompletion= new Completion__c(CaliberID__c='5', Challenge__c=achallenge.Id);
        insert acompletion;

        Test.startTest();
        SUC.updateDatabase();
        Test.stopTest();

        Contact[] internalAssociates = [SELECT Id, Name FROM Contact WHERE recordType.Name IN ('Associate')];
        Account[] internalBatches = [SELECT Name, BatchId__c FROM Account WHERE recordType.Name IN ('Batch')];
        Challenge__c[] challenges = [SELECT Id,Name FROM Challenge__c];
        Stack__c[] stacks = [SELECT Id,Name FROM Stack__c];
        Completion__c[] completions = [SELECT Id, Name FROM Completion__c];
        
        //System.debug('Internal Associates: ' + internalAssociates);
        //System.debug('Internal Batches: ' + internalBatches);
        System.assertEquals(4, internalAssociates.size());
        System.assertEquals(7, internalBatches.size());
        System.assertEquals(3, challenges.size());
        System.assertEquals(2, stacks.size());
        System.assertEquals(3, completions.size());
    }

    @isTest
    private static void testGetCategories(){
        SyncUtilityClass SUC = new SyncUtilityClass();
        Test.setMock(HttpCalloutMock.class, new SyncCalloutMock());

        Test.startTest();
        Stack__c[] stacks = SUC.getCategories();
        Test.stopTest();

        System.assertEquals(2,stacks.size());
    }

    @isTest
    private static void testGetAssessments(){
        SyncUtilityClass SUC = new SyncUtilityClass();
        Test.setMock(HttpCalloutMock.class, new SyncCalloutMock());

        Test.startTest();
        Challenge__c[] challenges = SUC.getAssessments([SELECT Id,BatchId__c FROM Account WHERE recordType.Name IN ('Batch')]);
        Test.stopTest();
        
        System.assertEquals(3,challenges.size());
    }
}