force-app/main/default/objects/Account/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stack__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Testing</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>Aura/Lightning Components</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Declarative Salesforce</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>SOQL/SOSL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Spring</fullName>
            </value>
            <value>
                <fullName>Typescript</fullName>
            </value>
            <value>
                <fullName>HTML/CSS</fullName>
            </value>
            <value>
                <fullName>Node.Js</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateMockPanelControllerTest.cls
@isTest
public class CreateMockPanelControllerTest {

@isTest
public static void getTypePicklistValuesTest() {
     User testUser = [SELECT id FROM User WHERE lastName='Carlson']; 
     System.debug(testUser);
     Map<String,List<String>> returnedMap = new Map<String,List<String>>();

     System.runAs(testUser) {
     returnedMap = CreateMockPanelController.getTypePicklistValues();
     }

    List<String> salesforceTypes = new List<String>{'Apex', 'Apex Trigger','Apex Testing', 'Visualforce','Aura/Lightning Components', 'Declarative Salesforce', 'SOQL/SOSL', 'HTML/CSS', 'JavaScript'};
    List<String> javaTypes = new List<String>{'Java', 'React', 'Spring', 'Typescript', 'Node.Js', 'JavaScript'};
    List<String> netTypes = new List<String>{'C#', 'C++', 'SQL', 'JavaScript', 'Python', 'C'};
    List<String> PCTypes = new List<String>{'Fun'};
    Map<String, List<String>> testMap = new Map<String, List<String>>{'Salesforce'=> salesforceTypes, 'Java'=> javaTypes, '.NET'=> netTypes, 'Pop Culture' => PCTypes};
    System.assertEquals(testMap, returnedMap);
}

@TestSetup
static void makeQuestions(){
    List<Question__c> allQuestions = new List<Question__c>();
    for (Integer i= 0; i<100; i++) {
        Integer mod = Math.mod(i,3);
        Question__c question = new Question__c();
        switch on mod {
            when 0 {

                question.Stack__c='Salesforce';
                question.Type__c='Apex';

            }
            when 1 {
                
                question.Stack__c='Salesforce';
                question.Type__c='Visualforce';

            }
            when 2 {
                
                question.Stack__c='Java';
                question.Type__c='Java';
            }

        }
        allQuestions.add(question);
    }
    insert allQuestions;

    Account testAcc = new Account();
    testAcc.name = 'test company';
    Database.SaveResult savedAccount = Database.insert(testAcc);
    Id accID = savedAccount.getId();
    
    
    Contact con = new Contact(lastname = 'stuff', AccountId = accId);
    Database.SaveResult savedContact = Database.insert(con);

    Id contId = savedContact.getId();
    Profile prof = [SELECT id FROM Profile WHERE Name = 'Associate'];
    
    User u = new User(firstName = 'test1', lastName ='stuff', profileId = prof.id, 
                        username = 'test@test.com', email = 'test@test.com', ContactId = contId,
                        alias= 'Test', TimeZoneSidKey='America/New_York', LocaleSidKey='en_US',
                        EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', IsActive = true);
    insert u;
}

@isTest
public static void createMockPanelPositiveTest() {
    List<String> testObject = new List<String>{'Java', 'Apex', 'Visualforce'};
    List<Integer> results = CreateMockPanelController.getNumberOfQuestionType(testObject);
    System.assertEquals(3, results.size());
    System.assertEquals(33, results[0]);
    System.assertEquals(34, results[1]);
    System.assertEquals(33, results[2]);
}

@isTest
public static void createMockPanelNegativeTest() {
    List<String> testObject = new List<String>{'Banana', 'Egg', 'potato'};
    List<Integer> results = CreateMockPanelController.getNumberOfQuestionType(testObject);
    System.assertEquals(3, results.size());
    System.assertEquals(0, results[0]);
    System.assertEquals(0, results[1]);
    System.assertEquals(0, results[2]);
}

@isTest static void createMockPanelNullTest() {
    List<String> testObject = new List<String>();
    List<Integer> results = CreateMockPanelController.getNumberOfQuestionType(testObject);
    System.assertEquals(0, results.size());
}
}