force-app/main/default/objects/Account/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Batch.recordType-meta.xml
<RecordType>
    <fullName>Batch</fullName>
    <active>true</active>
    <label>Batch</label>
</RecordType>

miaCreateMeetingComp/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stack__c/User_Stack__c.object-meta.xml
<CustomObject>
    <description>The Stack to User assignment Object.</description>
    <label>User Stack</label>
    <nameField>
        <displayFormat>UseS-{000000}</displayFormat>
        <label>User Stack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stack__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>User Stacks</relationshipLabel>
    <relationshipName>User_Stacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

interview-board-administration/main/default/classes/AssignStacksPageTest.cls
@isTest
public class AssignStacksPageTest {
    @TestSetup
    static void makeData(){
        //set Account Portal Owner
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        system.debug('portalRole is ' + portalRole);
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
        UserRoleId = portalRole.Id,
        ProfileId = profile1.Id,
        Username = System.now().millisecond() + 'test2@test.com',
        Alias = 'batman',
        Email='bruce.wayne@wayneenterprises.com',
        EmailEncodingKey='UTF-8',
        Firstname='Bruce',
        Lastname='Wayne',
        LanguageLocaleKey='en_US',
        LocaleSidKey='en_US',
        TimeZoneSidKey='America/Chicago'
        );
        Database.insert(portalAccountOwner1);

        System.runAs(portalAccountOwner1){
            //create Client
            Account testClient = new Account(Name='Test Client');
            insert testClient;

            //create Batch
            Account testBatch = new Account(Name='Test Batch',
                                                OwnerId = portalAccountOwner1.Id
                                            );
            insert testBatch;

            //create Associate/User
            Profile testProfile = [SELECT Id FROM Profile WHERE Name='Associate'];
            Id testRecordTypeId = [SELECT Id FROM RecordType WHERE Name='Associate' LIMIT 1].Id;
            Contact testAssociate = new Contact(LastName ='UserT',
                                                    RecordTypeId=testRecordTypeId,
                                                    AccountId=testBatch.Id);
            insert testAssociate;
            User testUser = new User(Alias='standt',
                                        Email='testAssignStackuser@testorg.com',
                                        EmailEncodingKey='UTF-8',
                                        LastName='Testing',
                                        LanguageLocaleKey='en_US',
                                        LocaleSidKey='en_US',
                                        ProfileId = testProfile.Id,
                                        Username='testAssignStackuser@testorg.com',
                                        TimeZoneSidKey='America/Los_Angeles',
                                        ContactId=testAssociate.Id
                                    );
            insert testUser;

            //create Stack
            Stack__c testStack = new Stack__c(Name='Test Stack');
            insert testStack;
        }

    }

    @isTest
    static void AssociateSearchTest() {
        List<Contact> returnedAssociates = AssignStacksPageController.AssociateSearch('UserT');
        System.assertNotEquals(null, returnedAssociates, 'There is an issue with the returned associates');
    }

    @isTest
    static void StackSearchTest() {
        List<Stack__c> returnedStacks = AssignStacksPageController.StackSearch('Test Stack');
        System.assertNotEquals(null, returnedStacks, 'There is an issue with the returned stacks');
    }

    @isTest
    static void BatchSearchTest() {
        List<Account> returnedBatch = AssignStacksPageController.BatchSearch('Test Batch');
        System.assertNotEquals(null, returnedBatch, 'There is an issue with the returned batch');
    }

    @isTest
    static void SetUserStackTest() {
        List<Contact> returnedAssociates = AssignStacksPageController.AssociateSearch('UserT');
        List<Stack__c> returnedStacks = AssignStacksPageController.StackSearch('Test Stack');
        AssignStacksPageController.SetUserStack(returnedStacks, returnedAssociates[0].Id);
        List<User_Stack__c> results = [SELECT Id FROM User_Stack__c];
        System.assertNotEquals(null, results, 'There is an issue with the inserted stacks for the user');

    }

    @isTest
    static void SetBatchStackTest() {
        List<Account> returnedBatch = AssignStacksPageController.BatchSearch('Test Batch');
        List<Stack__c> returnedStacks = AssignStacksPageController.StackSearch('Test Stack');
        AssignStacksPageController.SetBatchStack(returnedStacks, returnedBatch[0].Id);
        List<User_Stack__c> results = [SELECT Id FROM User_Stack__c];
        System.assertNotEquals(null, results, 'There is an issue with the inserted stacks for the batch');

    }
}