force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stack__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Testing</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>Aura/Lightning Components</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Declarative Salesforce</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>SOQL/SOSL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Spring</fullName>
            </value>
            <value>
                <fullName>Typescript</fullName>
            </value>
            <value>
                <fullName>HTML/CSS</fullName>
            </value>
            <value>
                <fullName>Node.Js</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>The body of the response to this object</description>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Total_Votes__c.field-meta.xml
<CustomField>
    <fullName>Total_Votes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of votes that this response has.</description>
    <inlineHelpText>The total number of votes made on this response</inlineHelpText>
    <label>Total Votes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Upvotes__c.field-meta.xml
<CustomField>
    <fullName>Upvotes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of upvotes that this response has.</description>
    <inlineHelpText>How many people upvoted this response</inlineHelpText>
    <label>Upvotes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/Question_Response_Rating__c.object-meta.xml
<CustomObject>
    <description>A rating for the related question response</description>
    <label>Question Response Rating</label>
    <nameField>
        <displayFormat>R - {0}</displayFormat>
        <label>Question Response Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Response Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response_Rating__c/fields/Question_Response__c.field-meta.xml
<CustomField>
    <fullName>Question_Response__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The response that this rating refers to</description>
    <inlineHelpText>The response that this rating refers to</inlineHelpText>
    <label>Question Response</label>
    <referenceTo>Question_Response__c</referenceTo>
    <relationshipLabel>Question Response Ratings</relationshipLabel>
    <relationshipName>Question_Response_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>A rating of a response (upvote or downvote)</description>
    <inlineHelpText>Rate the response with an (upvote or downvote)</inlineHelpText>
    <label>Rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QuestionResponseRatingTriggerHandlerTest.cls
@isTest
public class QuestionResponseRatingTriggerHandlerTest {
    @isTest
    public static void deleteTest() {
        Question__c question = new Question__c(Body__c='Test Question', Stack__c='Salesforce',
                                               Type__c='Soft Skills');
        Question_Response__c response = new Question_Response__c(Body__c='Test Response', Question__c=question.Id);
        
        insert(question);
        insert(response);
        insert(new Question_Response_Rating__c(Question_Response__c=response.Id, Rating__c='1'));
        
        List<Question_Response_Rating__c> ratings = [SELECT Id, Rating__c FROM Question_Response_Rating__c];
        
        delete(ratings);
        
        List<Question_Response__c> responses = [SELECT Id, Total_Votes__c, Upvotes__c FROM Question_Response__c];
        
        System.assertEquals(0, responses[0].Total_Votes__c, 'The total number of votes was not adjusted correctly');
        System.assertEquals(0, responses[0].Upvotes__c, 'The total number of upvotes was not adjusted correctly');
        
    }
    @isTest
    public static void insertTest() {
        Question__c question = new Question__c(Body__c='Test Question', Stack__c='Salesforce',
                                               Type__c='Soft Skills');
        Question_Response__c response = new Question_Response__c(Body__c='Test Response', Question__c=question.Id);
        
        insert(question);
        insert(response);
        insert(new Question_Response_Rating__c(Question_Response__c=response.Id, Rating__c='1'));
        
        List<Question_Response__c> responses = [SELECT Id, Total_Votes__c, Upvotes__c FROM Question_Response__c];
        
        System.assertEquals(1, responses[0].Total_Votes__c, 'The total number of votes was not adjusted correctly');
        System.assertEquals(1, responses[0].Upvotes__c, 'The total number of upvotes was not adjusted correctly');
    }
    @isTest
    public static void updateTest() {
        Question__c question = new Question__c(Body__c='Test Question', Stack__c='Salesforce',
                                               Type__c='Soft Skills');
        Question_Response__c response = new Question_Response__c(Body__c='Test Response', Question__c=question.Id);
        
        insert(question);
        insert(response);
        insert(new Question_Response_Rating__c(Question_Response__c=response.Id, Rating__c='1'));
        
        List<Question_Response_Rating__c> ratings = [SELECT Id, Rating__c FROM Question_Response_Rating__c];
        
        ratings[0].Rating__c = '-1';
        update(ratings);
        
        List<Question_Response__c> responses = [SELECT Id, Total_Votes__c, Upvotes__c FROM Question_Response__c];
        
        System.assertEquals(1, responses[0].Total_Votes__c, 'The total number of votes was not adjusted correctly');
        System.assertEquals(0, responses[0].Upvotes__c, 'The total number of upvotes was not adjusted correctly');
    }
}