force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>The body of the response to this object</description>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Total_Rating__c.field-meta.xml
<CustomField>
    <fullName>Total_Rating__c</fullName>
    <formula>IF(Total_Votes__c == 0 ,0,(2 *  Upvotes__c -  Total_Votes__c) *  (IF((2 *  Upvotes__c -  Total_Votes__c) &gt; 0, Upvotes__c / Total_Votes__c, (1 -(Upvotes__c / Total_Votes__c))) ^ 3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Rating</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Total_Votes__c.field-meta.xml
<CustomField>
    <fullName>Total_Votes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of votes that this response has.</description>
    <inlineHelpText>The total number of votes made on this response</inlineHelpText>
    <label>Total Votes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Upvotes__c.field-meta.xml
<CustomField>
    <fullName>Upvotes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of upvotes that this response has.</description>
    <inlineHelpText>How many people upvoted this response</inlineHelpText>
    <label>Upvotes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/Question_Response_Rating__c.object-meta.xml
<CustomObject>
    <description>A rating for the related question response</description>
    <label>Question Response Rating</label>
    <nameField>
        <displayFormat>R - {0}</displayFormat>
        <label>Question Response Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Response Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response_Rating__c/fields/Question_Response__c.field-meta.xml
<CustomField>
    <fullName>Question_Response__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The response that this rating refers to</description>
    <inlineHelpText>The response that this rating refers to</inlineHelpText>
    <label>Question Response</label>
    <referenceTo>Question_Response__c</referenceTo>
    <relationshipLabel>Question Response Ratings</relationshipLabel>
    <relationshipName>Question_Response_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>A rating of a response (upvote or downvote)</description>
    <inlineHelpText>Rate the response with an (upvote or downvote)</inlineHelpText>
    <label>Rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/responseController.cls
public class responseController {
    
    @AuraEnabled
    public static String getQuestion(String questionID){
        //String questionId = [SELECT Name From Question__c LIMIT 1].Name;
        //System.debug(questionId);
        String randomQuestion = [SELECT Name, Body__c From Question__c WHERE Name =: questionID LIMIT 1].Body__c;
        return randomQuestion;
        
    }
    
    
    @AuraEnabled
    public static void addResponse(String body, String questionBody){
       Question__c q = [SELECT id FROM Question__c WHERE Body__c =: questionBody LIMIT 1 ];
        id test = q.id;
        Question_Response__c newResponse= new Question_Response__c();
        newResponse.Body__c = body;
        
        newResponse.Question__c=test;
        insert(newResponse);
    }
    
    @AuraEnabled
    public static void rateResponse(String name, Integer rating){
       Question_Response__c qr = [SELECT id, Total_Votes__c, Upvotes__c FROM Question_Response__c WHERE Name =: name LIMIT 1 ];
       Question_Response_Rating__c[] qrrs = [SELECT id, Rating__c FROM Question_Response_Rating__c WHERE Question_Response__c =: qr.Id];
       Question_Response_Rating__c qrr;
        if(qrrs.size() > 0){
           qrr = qrrs[0]; 
        } else {
           qrr = new Question_Response_Rating__c();
           qrr.Question_Response__c = qr.Id;
        }
        System.debug(qrr);
        if((rating == 1 && qrr.Rating__c == '1') || (rating == -1 && qrr.Rating__c == '-1')){
            delete qrr;
        } else {
            if(rating > 0){
                qrr.Rating__c = '1';
            } else {
                qrr.Rating__c = '-1';
            }
            upsert qrr;
        }
    }
    
    @AuraEnabled
    public static List<Question_Response_Rating__c> getUserVotes(){
        return [SELECT Name, Question_Response__r.Name, Rating__c FROM Question_Response_Rating__c WHERE CreatedById =: UserInfo.getUserId()];
    }
    
    @AuraEnabled
    public static List<Question_Response__c> getResponse(String questionBody){
         id question = [SELECT id FROM Question__c WHERE Body__c =: questionBody LIMIT 1 ].id;
        
        List<Question_Response__c> responseList = [SELECT Name, Body__c, CreatedBy.Name, CreatedDate, Upvotes__c, Total_Votes__c FROM Question_Response__c WHERE Question__c=:question ORDER By Total_Rating__c DESC];
        System.debug(responseList);
        return responseList;
        
    }
    
    

}