force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Locked__c.field-meta.xml
<CustomField>
    <fullName>Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes the question has responses locked.</description>
    <inlineHelpText>Prevent responses from being added to this question.</inlineHelpText>
    <label>Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stack__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Testing</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>Aura/Lightning Components</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Declarative Salesforce</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>SOQL/SOSL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Spring</fullName>
            </value>
            <value>
                <fullName>Typescript</fullName>
            </value>
            <value>
                <fullName>HTML/CSS</fullName>
            </value>
            <value>
                <fullName>Node.Js</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>The body of the response to this object</description>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Upvotes__c.field-meta.xml
<CustomField>
    <fullName>Upvotes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of upvotes that this response has.</description>
    <inlineHelpText>How many people upvoted this response</inlineHelpText>
    <label>Upvotes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QuestionPoolApexControllerTest.cls
@isTest
public class QuestionPoolApexControllerTest {
    @TestSetup
    static void makeData(){
        List<Question__c> allQuestions = new List<Question__c>();
        List<Question_Response__c> allResponses = new List<Question_Response__c>();
        Question__c question;
        for (Integer i= 0; i<300; i++) {
            String Qname = 'Test Question ' + i;
            allQuestions.add(new Question__c( Body__c = Qname, Stack__c='Salesforce',Type__c='Apex', Locked__c = false));
        }
        insert allQuestions;
        
        //add responses
        for(Integer i=0; i<300; i++){
            String respBody = 'Test Response ' + i;
            allResponses.add(new Question_Response__c( Body__c = respBody, Question__c=allQuestions[i].Id, Upvotes__c=i) );
        }
        insert allResponses;
    }

    @isTest
    public static void getQuestionPoolPositiveTest() {
        List<Question__c> qList = QuestionPoolApexController.getQuestionPool();
        System.assertEquals(300, qList.size());
    }

    @isTest
    public static void deleteQuestionsPositiveTest() {
        Question__c question = [SELECT Id FROM Question__c WHERE Body__c='Test Question 37'];
        String qId = question.Id;
        System.assertEquals(300, [SELECT Id FROM Question__c].size());
        QuestionPoolApexController.deleteQuestions(new List<String>{qId});
        System.assertEquals(299, [SELECT Id FROM Question__c].size());
    }

    @isTest
    public static void deleteQuestionsNegative2DeletesTest() {
        Question__c question = [SELECT Id FROM Question__c WHERE Body__c='Test Question 58'];
        String qId = question.Id;
        System.assertEquals(300, [SELECT Id FROM Question__c].size());
        QuestionPoolApexController.deleteQuestions(new List<String>{qId});
        QuestionPoolApexController.deleteQuestions(new List<String>{qId});
        System.assertEquals(299, [SELECT Id FROM Question__c].size());
    }

    @isTest
    public static void deleteQuestionsNegativeNullTest() {
        System.assertEquals(300, [SELECT Id FROM Question__c].size());
        QuestionPoolApexController.deleteQuestions(new List<String>{null});
        System.assertEquals(300, [SELECT Id FROM Question__c].size());
    }

    @isTest
    public static void deleteQuestionsPositiveBulkTest() {
        List<String> questionNames = new List<String>();
        for (Integer i= 0; i<100; i++) {
            questionNames.add('Test Question '+i);
        }
        List<Question__c> questions = [SELECT Id FROM Question__c WHERE Body__c IN :questionNames];
        List<String> idList = new List<String>();
        for(Question__c q : questions) {
            idList.add(q.Id);
        }
        System.assertEquals(300, [SELECT Id FROM Question__c].size());
        QuestionPoolApexController.deleteQuestions(idList);
        System.assertEquals(200, [SELECT Id FROM Question__c].size());
    }

    @isTest
    public static void deleteQuestionsNegativeBulkTest() {
        List<String> questionNames = new List<String>();
        for (Integer i= 0; i<100; i++) {
            questionNames.add('Test Question '+i);
        }
        List<Question__c> questions = [SELECT Id FROM Question__c WHERE Body__c IN :questionNames];
        List<String> idList = new List<String>();
        for(Question__c q : questions) {
            idList.add(q.Id);
        }
        String singleId = idList[0];

        System.assertEquals(300, [SELECT Id FROM Question__c].size());
        QuestionPoolApexController.deleteQuestions(new String[]{singleId});
        System.assertEquals(299, [SELECT Id FROM Question__c].size());
        QuestionPoolApexController.deleteQuestions(idList);
        System.assertEquals(200, [SELECT Id FROM Question__c].size());
    }
   
    //getting responses
    @isTest
    public static void getResponsesPositiveTest() {
        List<Question__c> ques = [SELECT id FROM Question__c];
        List<id> ids = new List<id>();
        
        for(Question__c q : ques){
            ids.add(q.Id);
        }
        
        List<Question_Response__c> rList = QuestionPoolApexController.getResponses(ids);
        System.assertEquals(300, rList.size());
    }
    
    //deleting responses
	@isTest
    public static void deleteResponsesPositiveTest() {
        List<Question_Response__c> response = [SELECT Id FROM Question_Response__c WHERE Upvotes__c = 27];
        //get ids from query
        List<id> ids = new List<id>();
        
        for(Question_Response__c r : response){
            ids.add(r.Id);
        }
        
        System.assertEquals(300, [SELECT Id FROM Question_Response__c].size());
        QuestionPoolApexController.deleteResponses(ids);
        System.assertEquals(299, [SELECT Id FROM Question_Response__c].size());
    }
    
    //lock responses
    @isTest
    public static void lockQuestionsPositiveTest() {
        //get ids
        List<Question__c> ques = [SELECT id, Locked__c FROM Question__c];
        List<id> ids = new List<id>();
        
        for(Question__c q : ques){
            ids.add(q.Id);
        }
        
        //lock and check
        QuestionPoolApexController.lockQuestions(ids);
        //requery
        ques = [SELECT id, Locked__c FROM Question__c];
        
        for(Question__c q : ques){
            System.assertEquals( true, q.Locked__c );
        }
        
        //unlock and check
        QuestionPoolApexController.lockQuestions(ids);
        //requery
        ques = [SELECT id, Locked__c FROM Question__c];
        
        for(Question__c q : ques){
            System.assertEquals( false, q.Locked__c );
        }
    }
}