force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stack__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Testing</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>Aura/Lightning Components</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Declarative Salesforce</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>SOQL/SOSL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Spring</fullName>
            </value>
            <value>
                <fullName>Typescript</fullName>
            </value>
            <value>
                <fullName>HTML/CSS</fullName>
            </value>
            <value>
                <fullName>Node.Js</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>The body of the response to this object</description>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/Question_Response_Rating__c.object-meta.xml
<CustomObject>
    <description>A rating for the related question response</description>
    <label>Question Response Rating</label>
    <nameField>
        <displayFormat>R - {0}</displayFormat>
        <label>Question Response Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Response Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response_Rating__c/fields/Question_Response__c.field-meta.xml
<CustomField>
    <fullName>Question_Response__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The response that this rating refers to</description>
    <inlineHelpText>The response that this rating refers to</inlineHelpText>
    <label>Question Response</label>
    <referenceTo>Question_Response__c</referenceTo>
    <relationshipLabel>Question Response Ratings</relationshipLabel>
    <relationshipName>Question_Response_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>A rating of a response (upvote or downvote)</description>
    <inlineHelpText>Rate the response with an (upvote or downvote)</inlineHelpText>
    <label>Rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/responseControllerTest.cls
@isTest
public class responseControllerTest {
    
	@isTest
    public static void Test(){
        String questionBody = 'What day of the week is it?';
        String body = 'This is an example response.';
        List<Question_Response_Rating__c> ratingList = new List<Question_Response_Rating__c>();
        
        // This function currently grabs the body of first question in the question pool
        Question__c question = responseController.getQuestion('Q-100043');
        System.assertEquals('What day of the week is it?', question.body__c);
        
        // This function adds a response into the database
        responseController.addResponse(body, questionBody);
        
        // This functions rates the response we added with an upvote
        responseController.rateResponse('QR-100027', 1);
        ratingList = responseController.getUserVotes();
        System.assertEquals(1, Integer.valueOf(ratingList[0].Rating__c));
        
        // This functions rates the response we added with another upvote
        responseController.rateResponse('QR-100027', 1);
        ratingList = responseController.getUserVotes();
        
        // This functions rates the response we added with a downvote
        responseController.rateResponse('QR-100027', -1);
        ratingList = responseController.getUserVotes();
        System.assertEquals(-1, Integer.valueOf(ratingList[0].Rating__c));
        
        // This function gets a list of responses based on the question passed in to it
        List<Question_Response__c> rList = responseController.getResponse(questionBody);
        
        // Loop through all of the responses for our question, and make sure they were populated correctly.
        Integer iteration = 0;
        for(Question_Response__c qR : rList){
            System.assertEquals(qR.Body__c, (rList[iteration].Body__c));
            iteration++;
        }
    }
    
    // This method is run to create dummy data used in the test
    @testSetup
    static void makeData(){
        
        // Initialize a dummy question
        Question__c q = new Question__c();
        q.Body__c = 'What day of the week is it?';
        q.Stack__c = 'Salesforce';
        q.Type__c = 'Soft Skills';
        
        insert q;
        
        Question__c qq = [SELECT Name, Body__c FROM Question__c LIMIT 1];
        
        System.debug(qq);
        
        
        // Initialize 2 dummy responses
        List<Question_Response__c> r = new List<Question_Response__c>();
        String questionBody = 'What day of the week is it?';
        id question = [SELECT id FROM Question__c WHERE Body__c =: questionBody LIMIT 1 ].id;
        
        for(Integer i = 1; i <= 2; i++) {
        	Question_Response__c resp = new Question_Response__c(); 
            resp.Body__c = 'This is response #' + i;
            resp.Question__c = question;
            r.add(resp);
        }
        insert r;
    }
}