miaCreateMeetingComp/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Batch_Client__c/Batch_Client__c.object-meta.xml
<CustomObject>
    <label>Batch Client</label>
    <nameField>
        <label>Batch Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Client__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch Clients</relationshipLabel>
    <relationshipName>Batch_Clients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Interview_Question__c/Interview_Question__c.object-meta.xml
<CustomObject>
    <label>Interview Question</label>
    <nameField>
        <label>Interview Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview_Question__c/fields/Meeting_md__c.field-meta.xml
<CustomField>
    <fullName>Meeting_md__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions (Meeting)</relationshipLabel>
    <relationshipName>Interview_Questions1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interview_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

packageTest/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Meeting</relationshipLabel>
    <relationshipName>Meeting</relationshipName>
    <type>Lookup</type>
</CustomField>

packageTest/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

packageTest/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

package/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

interview-board-administration/main/default/classes/TestDataCreationTest.cls
@isTest
public with sharing class TestDataCreationTest {
    
    @isTest
    public static void resetTest()
    {
        //Generates the test data from TestDataCreation Class
        Test.startTest();
        TestDataCreation.reset();
        Test.stopTest();

        //Fills the objs variable with the data created
        List<List<sObject>> objs = new List<List<sObject>>();
        objs.add([SELECT Id, (SELECT Id FROM Contacts), Account.RecordType.Name FROM Account]);
        objs.add([SELECT Id FROM Batch_Client__c]);
        objs.add([SELECT Id, Batch__c, (SELECT Id FROM Meeting_Participants__r), (SELECT Id FROM Interview_Questions1__r), RecordType.Name FROM Meeting__c]);
        objs.add([SELECT Id FROM Question__c]);

        Map<Id, List<Contact>> batMap = new Map<Id, List<contact>>();

        //Did the 15 contacts get inserted?
        System.assertEquals(15, objs.get(0).size());
        for(Account a : (List<Account>)objs.get(0))
        {
            batMap.put(a.Id, a.Contacts);
            if(a.RecordType.Name == 'Client')
            {
                System.assert(1 <= a.Contacts.size());
                System.assert(3 >= a.Contacts.size());
            }
            else
            {
                System.assert(10 <= a.Contacts.size());
                System.assert(20 >= a.Contacts.size());
            }
        }
        System.assert(15 <= objs.get(1).size());
        System.assert(19 >= objs.get(1).size());

        System.assert(60 <= objs.get(2).size());
        System.assert(120 >= objs.get(2).size());

        for(Meeting__c m : (List<Meeting__c>)objs.get(2))
        {
            if(m.RecordType.Name == 'Invertention 1-1' || m.RecordType.Name == 'Interview 1-1')
                System.assert(2 == m.Meeting_Participants__r.size());
            else
            {
                System.assert(2 <= m.Meeting_Participants__r.size());
            }

            System.assert(4 <= m.Interview_Questions1__r.size());
        }
        System.assert(20 <= objs.get(3).size());
    }
}