force-app/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <description>The specific task that a User would need to complete to get credit to be used for their overall score.</description>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Session__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <label>Date and Time</label>
    <type>DateTime</type>
</CustomField>

package/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>sfqz__Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sfqz__Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactorySessions.cls
public with sharing class DataFactorySessions {
       	//phase picklist options may change over time ; user input string allows for flexibility and reuse in future. 
           public static void makeSessions (Integer Num, String phaseString, String phaseString2, String phaseString3) {
            List<Quiz_Session__c> quizzes = new List<Quiz_Session__c>();
            
                for(Integer i=0; i < Num; i++) {
            Quiz_Session__c newS = new Quiz_Session__c(Phase__c= phaseString, Date_and_Time__c = System.now());
            quizzes.add(newS);
               Quiz_Session__c newS1 = new Quiz_Session__c(Phase__c= phaseString2, Date_and_Time__c = System.now());
             quizzes.add(newS1);
             Quiz_Session__c newS2 = new Quiz_Session__c(Phase__c= phaseString3, Date_and_Time__c = System.now());
             quizzes.add(newS2);
                }
    insert quizzes;
    }
}