force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Total_Votes__c.field-meta.xml
<CustomField>
    <fullName>Total_Votes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of votes that this response has.</description>
    <inlineHelpText>The total number of votes made on this response</inlineHelpText>
    <label>Total Votes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Upvotes__c.field-meta.xml
<CustomField>
    <fullName>Upvotes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of upvotes that this response has.</description>
    <inlineHelpText>How many people upvoted this response</inlineHelpText>
    <label>Upvotes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/Question_Response_Rating__c.object-meta.xml
<CustomObject>
    <description>A rating for the related question response</description>
    <label>Question Response Rating</label>
    <nameField>
        <displayFormat>R - {0}</displayFormat>
        <label>Question Response Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Response Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response_Rating__c/fields/Question_Response__c.field-meta.xml
<CustomField>
    <fullName>Question_Response__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The response that this rating refers to</description>
    <inlineHelpText>The response that this rating refers to</inlineHelpText>
    <label>Question Response</label>
    <referenceTo>Question_Response__c</referenceTo>
    <relationshipLabel>Question Response Ratings</relationshipLabel>
    <relationshipName>Question_Response_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>A rating of a response (upvote or downvote)</description>
    <inlineHelpText>Rate the response with an (upvote or downvote)</inlineHelpText>
    <label>Rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionResponseRatingTriggerHandler.cls
public class QuestionResponseRatingTriggerHandler {
    public static void deleteRating(List<Question_Response_Rating__c> ratings) {
        for (Question_Response_Rating__c rating : ratings) {
            Id responseId = rating.Question_Response__c;
            Question_Response__c response = [SELECT Total_Votes__c, Upvotes__c FROM Question_Response__c
                                             WHERE Id =: responseId];
            response.Total_Votes__c--;
            if (rating.Rating__c == '1') {
                response.Upvotes__c--;
            }
            
            update response;
        }
    }
    public static void insertRating(List<Question_Response_Rating__c> ratings) {
        for (Question_Response_Rating__c rating : ratings) {
            Id responseId = rating.Question_Response__c;
            Question_Response__c response = [SELECT Total_Votes__c, Upvotes__c FROM Question_Response__c
                                             WHERE Id =: responseId];
            
            // Update the associated Question_Response__c total votes and number of upvotes fields
            // before the Question_Response_Rating__c is inserted into the database
            response.Total_Votes__c++;
            if (rating.Rating__c == '1') {
                   response.Upvotes__c++;
            }
                
            update response;
        }
    }
    public static void updateRating(List<Question_Response_Rating__c> ratings) {
        for (Question_Response_Rating__c rating : ratings) {
            Id responseId = rating.Question_Response__c;
            Question_Response__c response = [SELECT Total_Votes__c, Upvotes__c FROM Question_Response__c
                                             WHERE Id =: responseId];
        
        if (rating.Rating__c == '-1') {
            response.Upvotes__c -= 1;
        } else {
            response.Upvotes__c += 1;
        }
        
        update response;
        }
    }
}