force-app/main/default/objects/Interview_Question__c/Interview_Question__c.object-meta.xml
<CustomObject>
    <label>Interview Question</label>
    <nameField>
        <label>Interview Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>144</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuestionCreationController.cls
//Interview Question Object Controller
//Responds to Aura Component- QuestionCreation

public class QuestionCreationController {

    //Save a record that a user has created from corresponding QuestionCreation.cmp
    @AuraEnabled
    public static void saveQuestion(String subject, String question){
        try{
             Interview_Question__c iq = new Interview_Question__c(Body__c = question, Subject__c = subject);
             insert iq;
        }catch(Exception e){
             System.debug(e.getMessage());
        }
    }
}