force-app/main/default/objects/Interview_Question__c/Interview_Question__c.object-meta.xml
<CustomObject>
    <label>Interview Question</label>
    <nameField>
        <label>Interview Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/fields/Meeting_md__c.field-meta.xml
<CustomField>
    <fullName>Meeting_md__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions (Meeting)</relationshipLabel>
    <relationshipName>Interview_Questions1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MockInterviewLauncher.cls
public with sharing class MockInterviewLauncher {
    public MockInterviewLauncher() {

    }
    @auraenabled
    public static List<Interview_Question__c> GetInterviewQuestions(String meetingid) {
        //returns all interview_question objects that are related to the parameter meetingid 
        List<Interview_Question__c> returnlist = new List<Interview_Question__c>{};

        try {
            //name, body__c fields removed as these are no longer used on the Interview_Question__c object
            returnlist = [SELECT id FROM Interview_Question__c WHERE Meeting_md__c = : meetingid];
        
        } catch(Exception e) {
                throw new AuraHandledException('Server-side Error: ' + e.getMessage()); 
        }

        return returnlist;
    }
}