force-app/main/default/objects/Interview_Question__c/Interview_Question__c.object-meta.xml
<CustomObject>
    <label>Interview Question</label>
    <nameField>
        <label>Interview Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stack__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Testing</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>Aura/Lightning Components</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Declarative Salesforce</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>SOQL/SOSL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Spring</fullName>
            </value>
            <value>
                <fullName>Typescript</fullName>
            </value>
            <value>
                <fullName>HTML/CSS</fullName>
            </value>
            <value>
                <fullName>Node.Js</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateMockInterviewControllerTest.cls
@isTest
public class CreateMockInterviewControllerTest {
    @isTest
    public static void getTypePicklistValuesTest() {
        Map<String,List<String>> returnedMap = CreateMockInterviewController.getTypePicklistValues();
        List<String> salesforceTypes = new List<String>{'Soft Skills','Apex', 'Apex Trigger','Apex Testing', 'Visualforce','Aura/Lightning Components', 'Declarative Salesforce', 'SOQL/SOSL', 'HTML/CSS', 'JavaScript'};
        List<String> javaTypes = new List<String>{'Soft Skills', 'Java', 'React', 'Spring', 'Typescript', 'Node.Js', 'JavaScript'};
        List<String> netTypes = new List<String>{'Soft Skills', 'C#', 'C++', 'SQL', 'JavaScript', 'Python', 'C'};
        Map<String, List<String>> testMap = new Map<String, List<String>>{'Salesforce'=> salesforceTypes, 'Java'=> javaTypes, '.NET'=> netTypes};
        System.assertEquals(testMap, returnedMap);
    }

    @TestSetup
    static void makeQuestions(){
        List<Question__c> allQuestions = new List<Question__c>();
            for (Integer i= 0; i<100; i++) {
                Integer mod = Math.mod(i,3);
                Question__c question = new Question__c();
                switch on mod {
                    when 0 {

                        question.Name= 'Apex'+i;
                        question.Stack__c='Salesforce';
                        question.Type__c='Apex';

                    }
                    when 1 {
                        question.Name='Visualforce'+i;
                        question.Stack__c='Salesforce';
                        question.Type__c='Visualforce';

                    }
                    when 2 {
                        question.Name='Java'+i;
                        question.Stack__c='Java';
                        question.Type__c='Java';
                    }

                }
                allQuestions.add(question);
            }
            insert allQuestions;
    }

    @isTest
    public static void createMockInterviewPositiveTest() {
        List<String> types = new List<String>{'Apex', 'Visualforce'};
        CreateMockInterviewController.createMockInterview(20, types);
        Integer gotQuestions = [SELECT COUNT() FROM Interview_Question__c WHERE Meeting__r.Name = 'Mock interview with 20 questions'];
        //AggregateResult numQuestion = gotQuestions[0];
        System.assertEquals(20, gotQuestions);
    }
    @isTest
    public static void createMockInterviewNegativeTest() {
        List<String> types = new List<String>{'Apex', 'Visualforce'};
        CreateMockInterviewController.createMockInterview(null, types);
        Integer gotQuestions = [SELECT COUNT() FROM Interview_Question__c WHERE Meeting__r.Name = 'Mock interview with Null questions'];
        //AggregateResult numQuestion = gotQuestions[0];
        System.assertNotEquals(null, gotQuestions);
    }
}