force-app/main/default/objects/Interview_Question__c/Interview_Question__c.object-meta.xml
<CustomObject>
    <label>Interview Question</label>
    <nameField>
        <label>Interview Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview_Question__c/fields/Meeting_md__c.field-meta.xml
<CustomField>
    <fullName>Meeting_md__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions (Meeting)</relationshipLabel>
    <relationshipName>Interview_Questions1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interview_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stack__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Testing</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>Aura/Lightning Components</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Declarative Salesforce</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>SOQL/SOSL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Spring</fullName>
            </value>
            <value>
                <fullName>Typescript</fullName>
            </value>
            <value>
                <fullName>HTML/CSS</fullName>
            </value>
            <value>
                <fullName>Node.Js</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MockInterviewQuestionPoolControllerTest.cls
@isTest
public class MockInterviewQuestionPoolControllerTest {
    @testSetup
    static void setup(){
        //Create a test Mock Interview to hold the questions
        Id recordTypeId = Schema.sObjectType.Meeting__c.getRecordTypeInfosByName().get('Mock Interview').getRecordTypeId();
        Meeting__c testMeeting = new Meeting__c(Name = 'Test Meeting', RecordTypeId = recordTypeId);
        insert testMeeting;
        
        //Create Interview Questions for a Test Meeting
        Integer x = 3;
        Question__c[] questions = new Question__c[]{};
            For(Integer i=0; i < x; i++){
                questions.add(new Question__c(Name = 'Test', Stack__c = 'Salesforce', Type__c = 'Apex'));
            }
        insert questions;
        List<Interview_Question__c> interviewQuestions = new List<Interview_Question__c>();
        
        for (Integer k=0;k<x;k++) {
            Question__c quest = questions[k];
            interviewQuestions.add(new Interview_Question__c(Meeting_md__c = testMeeting.Id,
                                                             Question__c = quest.Id));
        }
        insert interviewQuestions;     
    }
    
    @isTest
    static void testGetQuestionPool(){
        //Get the meeting Id needed for the method call
        Meeting__c meeting = [SELECT Id FROM Meeting__c];
        Id ParentId = meeting.Id;
        Test.startTest();
        Interview_Question__c[] retrievedQuestions = MockInterviewQuestionPoolController.getQuestionPool(ParentId);
        Test.stopTest();
        //Check to see that the correct number of questions was retrieved from the list of Interview Questions.
        System.assertEquals(3, retrievedQuestions.size() );
    }
    
    @isTest
    static void testDeleteQuestions(){
        //Get the list of Interview Questions and delete all but 1 question. 
        List<Interview_Question__c> questions = [SELECT Id FROM Interview_Question__c];
        Id[] idList = new Id[]{};
            for(Integer i = 0; i<questions.size()-1; i++){
                idList.add(questions[i].Id);
            }
        List<Interview_Question__c> allQuestions = [SELECT Id FROM Interview_Question__c];
        Test.startTest();
        MockInterviewQuestionPoolController.deleteQuestions(idList);
        Test.stopTest();
        List<Interview_Question__c> afterTestQuestions = [SELECT Id FROM Interview_Question__c];
        //Check to see if the list size of the questions before the controller method call is not the same
        //as the list size of the questions after the controller method call.
        System.assertNotEquals(allQuestions.size(), afterTestQuestions.size());
        //Check to see that the correct number of questions was deleted from the list of Interview Questions.
        System.assertEquals(1, afterTestQuestions.size());
    }
}