force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Google_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Event_Id__c</fullName>
    <label>Google Event Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <label>Meeting Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Mock</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Schedule</fullName>
                <isActive>false</isActive>
                <label>On Schedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MeetingUtility.cls
@isTest
public class MeetingUtility {
    
    
    // Create meetings scheduled in google calendar
    
    public static List<Meeting__c> createScheduledMeetings(Integer numberToCreate){
        
    List<Meeting__c> meetings = new List<Meeting__c>();
       
        for(Integer i = 0; i < numberToCreate; i++){
            
            Meeting__c meeting = new Meeting__c();
            
            meeting.StartDateTime__c = Datetime.now().addMinutes(i);
            meeting.EndDateTime__c = meeting.StartDateTime__c.addHours(1);
            meeting.Meeting_Status__c = 'Scheduled';
            meeting.Google_Event_Id__c = 'bhrdutjfuhfe4ctlk33pt3o0lk';
            
            meetings.add(meeting);
        }
        return meetings;
    }
    
     // Create time slots not yet scheduled in google calendar nor chosen by associate
    
    public static List<Meeting__c> createTimeSlots(Integer numberToCreate, String stack){
        
    List<Meeting__c> meetings = new List<Meeting__c>();
       
        for(Integer i = 0; i < numberToCreate; i++){
            
            Meeting__c meeting = new Meeting__c();
            
            meeting.StartDateTime__c = Datetime.now().addMinutes(i);
            meeting.EndDateTime__c = meeting.StartDateTime__c.addHours(1);
            meeting.Meeting_Status__c = 'Not Scheduled';
            meeting.Google_Event_Id__c = null;
            meeting.Stack__c = stack;
            
            meetings.add(meeting);
        }
        return meetings;
    }
    
   // Create time slots chosen by an associate but not yet scheduled in google calendar
    
    public static List<Meeting__c> createApprovals(Integer numberToCreate, String stack){
        
    List<Meeting__c> meetings = new List<Meeting__c>();
       
        for(Integer i = 0; i < numberToCreate; i++){
            
            Meeting__c meeting = new Meeting__c();
            
            meeting.StartDateTime__c = Datetime.now().addMinutes(i);
            meeting.EndDateTime__c = meeting.StartDateTime__c.addHours(1);
            meeting.Meeting_Status__c = 'Awaiting Approval';
            meeting.Google_Event_Id__c = null;
            meeting.Stack__c = stack;
            
            meetings.add(meeting);
        }
        return meetings;
    }
}