force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <formula>Participating_Client__r.Participant__r.FirstName + &quot; &quot; + Participating_Client__r.Participant__r.LastName+ &quot;, &quot; + &quot;Company: &quot; + Participating_Client__r.Participant__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Google_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Event_Id__c</fullName>
    <label>Google Event Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <label>Meeting Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Mock</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Schedule</fullName>
                <isActive>false</isActive>
                <label>On Schedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VCCalendarController.cls
public without sharing class VCCalendarController {
    
    // Gets picklist values for all stack types
    
    @AuraEnabled
    public static List<String> getTypePicklistValues() {
        
        Map<String,List<String>> stackTypePicklistMap = Utilities.getTypePicklistValues();
        
        List<String> stackTypePicklist = new List<String>(stackTypePicklistMap.keySet());
        
        return stackTypePicklist;
    }
    
    
    // Gets the Id, Client Name, Start Time, and End Time of scheduled meetings
    
    @AuraEnabled
    public static Map<String, Meeting__c> getMeetings() {
        
        Map<String, Meeting__c> meetingDetails = new Map<String, Meeting__c>();
        
        List<Meeting__c> meetings = [SELECT Google_Event_Id__c, Client_Name__c, StartDateTime__c, EndDateTime__c FROM Meeting__c WHERE Google_Event_Id__c != null];
        
        if(meetings.size() > 0){
            
            for(Meeting__c meeting : meetings){
                
                meetingDetails.put(meeting.Google_Event_Id__c, meeting);
            }
        }
        return meetingDetails;   
    }
    
    // Converts start and end times associated with available time slots to a String for use in a picklist
    
    @AuraEnabled
    public static List<String> getTimeSlots() {
        
        List<String> timeSlots = new List<String>();
        
        List<Meeting__c> meetingTimeSlots = [SELECT StartDateTime__c, EndDateTime__c FROM Meeting__c WHERE Meeting_Status__c = 'Not Scheduled' AND Google_Event_Id__c = null];
        
        if(meetingTimeSlots.size() > 0){
            
            for(Meeting__c meeting : meetingTimeSlots){
                
                timeSlots.add(meeting.StartDateTime__c.format('MM/dd/yyyy HH:mm','America/New_York') + ' - ' + meeting.EndDateTime__c.format('HH:mm','America/New_York'));
            }
        }
        System.debug(timeSlots);
        return timeSlots;   
    }
    
    
     // Filters time slots and converts format for use in picklist
    
    @AuraEnabled
    public static List<String> getFilteredTimeSlots(String filter) {
        
        List<String> timeSlots = new List<String>();
        
        List<Meeting__c> meetingTimeSlots = [SELECT StartDateTime__c, EndDateTime__c FROM Meeting__c WHERE Meeting_Status__c = 'Not Scheduled' AND Google_Event_Id__c = null AND Stack__c = :filter];
        
        if(meetingTimeSlots.size() > 0){
            
            for(Meeting__c meeting : meetingTimeSlots){
                
                timeSlots.add(meeting.StartDateTime__c.format('MM/dd/yyyy HH:mm','America/New_York') + ' - ' + meeting.EndDateTime__c.format('HH:mm','America/New_York'));
            }
        }
        return timeSlots;   
    }
    
    // Change the meeting status for time slots not scheduled to awaiting approval
    
    @AuraEnabled
    public static List<String> setNeedsApprovalTimeSlots(String filter) {
        
        List<String> timeSlots = new List<String>();
        
        List<Meeting__c> meetingTimeSlots = [SELECT StartDateTime__c, EndDateTime__c FROM Meeting__c WHERE Meeting_Status__c = 'Not Scheduled' AND Google_Event_Id__c = null AND Stack__c = :filter];
        
        if(meetingTimeSlots.size() > 0){
            
            for(Meeting__c meeting : meetingTimeSlots){
                
                if((meeting.StartDateTime__c.format('MM/dd/yyyy HH:mm','America/New_York') + ' - ' + meeting.EndDateTime__c.format('HH:mm','America/New_York')) == filter){
                   
                    meeting.Meeting_Status__c = 'Awaiting Approval';
                    
                    timeSlots.add(meeting.StartDateTime__c.format('MM/dd/yyyy HH:mm','America/New_York') + ' - ' + meeting.EndDateTime__c.format('HH:mm','America/New_York'));
                }
            }
        }
        return timeSlots;   
    }

    @AuraEnabled
    public static Boolean hasScheduledMeetings() {
        
        Integer meeting = [SELECT Count() FROM Meeting__c WHERE Google_Event_Id__c != null];
        
        return (meeting > 0);   
    }
    
    @AuraEnabled
    public static Boolean hasUnScheduledTimeSlots() {
        
        Integer meeting = [SELECT Count() FROM Meeting__c WHERE Google_Event_Id__c = null];
        
        return (meeting > 0);   
    }
    
    // Determines wether the user has admin permissions to determine appropriate view
    
    @AuraEnabled
    public static Boolean getProfilePerm(){

        Boolean AdminPerm = FeatureManagement.checkPermission('AdminPermission');
        return AdminPerm;
    }
}