force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Participating_Client__c.field-meta.xml
<CustomField>
    <fullName>Participating_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participating Client</label>
    <referenceTo>Meeting_Participant__c</referenceTo>
    <relationshipLabel>Meeting</relationshipLabel>
    <relationshipName>Meeting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <label>Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/associateInterviewController.cls
public with sharing class associateInterviewController {
	@AuraEnabled
    public static List<Meeting__c> associateSearch(String associateId) {
		List<Meeting_Participant__c> participants;
		try {
			participants = [SELECT Meeting__r.Id FROM Meeting_Participant__c WHERE Participant__r.Id = :associateId];
		} catch (QueryException qe) {
			return new List<Meeting__c>();
		}
		List<Id> meetingIds = new List<Id>();
		for (Meeting_Participant__c p : participants) {
			meetingIds.add(p.Meeting__r.Id);
		}
		return [SELECT Id, Name, Scheduled__c FROM Meeting__c WHERE Id IN :meetingIds];
    }
}