force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <formula>Participating_Client__r.Participant__r.FirstName + &quot; &quot; + Participating_Client__r.Participant__r.LastName+ &quot;, &quot; + &quot;Company: &quot; + Participating_Client__r.Participant__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <label>Completed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssociateMeetingsController.cls
public with sharing class AssociateMeetingsController {
	@AuraEnabled
    public static List<Meeting__c> getMeetings(String AId) {
		list<Meeting_participant__C> MPList= [SELECT Meeting__C from Meeting_Participant__C where Participant__C = :AId];
        list<Meeting__C> MList = new List<Meeting__C>();
        for(Meeting_Participant__C MP : MPList){
			MList.add([SELECT Name, Completed_Date__c, Client_Name__C FROM Meeting__c WHERE Id = :MP.Meeting__c LIMIT 1]) ;
        }
        system.debug(mlist);
        return MList;
    }
}