force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MockInterviewsListController.cls
public with sharing class MockInterviewsListController {
    @AuraEnabled
    public static List<Meeting__c> getInterviews(){
        List<Meeting__c> yourInterviews = new List<Meeting__c>();
        ID userId = System.UserInfo.getUserId();
        User userContactId = [Select Contact.id FROM USER WHERE ID = :userId];
        List<Id> meetingIdList = new List<Id>();
        for(Meeting_Participant__c meetParti : [SELECT Meeting__c FROM Meeting_Participant__c WHERE Participant__c = :userContactId.Contact.Id]){

            MeetingIdList.add(meetParti.Meeting__c);
        }

        for (Meeting__c m : [SELECT Name, Notes__c FROM Meeting__c WHERE RecordType.Name = 'Mock Interview' AND Id IN :meetingIdList]) {
            yourInterviews.add(m);            
        }
        return yourInterviews;
    }
}