force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FullCalendarController.cls
public class FullCalendarController {

    @AuraEnabled
    public static List<Meeting__c> getMeetings() {
        Meeting__c newMeeting = new Meeting__c();
        newMeeting.EndDateTime__c = System.now();
        newMeeting.StartDateTime__c = System.now();
        newMeeting.Name = 'Test';
        insert newMeeting;
        
        return [SELECT EndDateTime__c, StartDateTime__c, Name, Id FROM Meeting__c];
    }
       
}