force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <label>Meeting Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Mock</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Schedule</fullName>
                <isActive>false</isActive>
                <label>On Schedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FullCalendarControllerTest.cls
@isTest
public class FullCalendarControllerTest {
    
    @isTest
    public static void getMeetingsTest() {
        // Create test meetings
        List<Meeting__c> meetingList = new List<Meeting__c>();
        
        for(Integer i=0; i<3; i++) {
            Meeting__c tMeeting = new Meeting__c();
            tMeeting.Name = 'Test ' + i;
            tMeeting.StartDateTime__c = System.now();
            tMeeting.EndDateTime__c = tMeeting.StartDateTime__c.addHours(1);
            tMeeting.Stack__c = 'Salesforce';
            meetingList.add(tMeeting);
        }
        
        meetingList.get(0).Meeting_Status__c = 'Not Scheduled';
        meetingList.get(1).Meeting_Status__c = 'Awaiting Approval';
        meetingList.get(2).Meeting_Status__c = 'Scheduled';
        
        insert meetingList;
        
        // Check for successful getMeetings()
        List<Meeting__c> retMeetings = FullCalendarController.getMeetings();
        
        System.assertEquals(retMeetings.get(0).Meeting_Status__c,'Not Scheduled');
        System.assertEquals(retMeetings.get(1).Meeting_Status__c,'Awaiting Approval');
        System.assertEquals(retMeetings.get(2).Meeting_Status__c,'Scheduled');
    }

}