force-app/main/default/objects/Challenge__c/Challenge__c.object-meta.xml
<CustomObject>
    <description>The specific task that a User would need to complete to get credit to be used for their overall score.</description>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Challenge__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Details and Requirements for the challenge to be meet.</description>
    <label>Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Challenge__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>The amount of points that a challenge is worth.</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Challenge__c/fields/Sub_Tech__c.field-meta.xml
<CustomField>
    <fullName>Sub_Tech__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The sub tech in which this specific challenge will be associated to.</description>
    <label>Sub Tech</label>
    <referenceTo>Sub_Tech__c</referenceTo>
    <relationshipLabel>Challenges</relationshipLabel>
    <relationshipName>Challenges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Completion__c/Completion__c.object-meta.xml
<CustomObject>
    <description>The Junction object for Challenges and User that is used to keep a record of completed challenges. Records of this object should be created when User is assigned a Stack.</description>
    <label>Completion</label>
    <nameField>
        <displayFormat>Comp-{0000000}</displayFormat>
        <label>Completion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Completion__c/fields/Challenge__c.field-meta.xml
<CustomField>
    <fullName>Challenge__c</fullName>
    <label>Challenge</label>
    <referenceTo>Challenge__c</referenceTo>
    <relationshipLabel>Completions</relationshipLabel>
    <relationshipName>Completions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Completion__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Challenge completed by the user?</description>
    <label>Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Completion__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sub_Tech__c/Sub_Tech__c.object-meta.xml
<CustomObject>
    <description>The specific tech in which the challenges would be made to cover.</description>
    <label>Sub Tech</label>
    <nameField>
        <label>Sub Tech Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Techs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/subTechButtonController.cls
public class subTechButtonController {
    @AuraEnabled
    public static List<Challenge__c> challenges(String curId){
        curId = (String) JSON.deserializeUntyped(curId);
        return [SELECT name,id,sub_tech__c,Details__c,Score__c FROM Challenge__c WHERE sub_tech__c=:curId];
    }
    
    @AuraEnabled
    public static List<Completion__c> completions(List<Challenge__c> challs){
        //curId = (String) JSON.deserializeUntyped(curId);
        return [SELECT name,id,Completed__C,Challenge__c FROM Completion__c WHERE Challenge__c in :challs];
    }
}