force-app/main/default/objects/Challenge__c/Challenge__c.object-meta.xml
<CustomObject>
    <description>The specific task that a User would need to complete to get credit to be used for their overall score.</description>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Challenge__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Details and Requirements for the challenge to be meet.</description>
    <label>Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Challenge__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>The amount of points that a challenge is worth.</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Challenge__c/fields/Sub_Tech__c.field-meta.xml
<CustomField>
    <fullName>Sub_Tech__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The sub tech in which this specific challenge will be associated to.</description>
    <label>Sub Tech</label>
    <referenceTo>Sub_Tech__c</referenceTo>
    <relationshipLabel>Challenges</relationshipLabel>
    <relationshipName>Challenges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Completion__c/Completion__c.object-meta.xml
<CustomObject>
    <description>The Junction object for Challenges and User that is used to keep a record of completed challenges. Records of this object should be created when User is assigned a Stack.</description>
    <label>Completion</label>
    <nameField>
        <displayFormat>Comp-{0000000}</displayFormat>
        <label>Completion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Completion__c/fields/Challenge__c.field-meta.xml
<CustomField>
    <fullName>Challenge__c</fullName>
    <label>Challenge</label>
    <referenceTo>Challenge__c</referenceTo>
    <relationshipLabel>Completions</relationshipLabel>
    <relationshipName>Completions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Completion__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Challenge completed by the user?</description>
    <label>Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Completion__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Completion__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Completions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub_Tech__c/Sub_Tech__c.object-meta.xml
<CustomObject>
    <description>The specific tech in which the challenges would be made to cover.</description>
    <label>Sub Tech</label>
    <nameField>
        <label>Sub Tech Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Techs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChallengeController.cls
public with sharing class ChallengeController {

    //this method is retriving detail from challenge__c object based on the Subtech selected and Challange inside that subject selected from dropdown and returing specific record
    @AuraEnabled
    public static list<challenge__c> challengeData(String recordid,String ChallangeName)
    {
        system.debug(recordid+'  '+ChallangeName);
        string soqlQuery ='select name,Details__c,Score__c,Sub_Tech__c from challenge__c where Sub_Tech__c= '+'\''+ recordid+'\''+' and name= '+'\''+ ChallangeName +'\'' +' limit 1';
       
        list<challenge__c> challengelist=database.query(soqlQuery);
        system.debug(challengelist);
        return challengelist;
       
    }
    
    
    //this method is retriving list of all the Challanges in challenge__c object based on Sub_Tech selected which is used to display Dropdown in component.
     @AuraEnabled
    public static list<challenge__c> challengeName(String recordid)
    {
        system.debug(recordid);
        string soqlQuery ='select name from challenge__c where Sub_Tech__c= '+'\''+ recordid+'\'';
        list<challenge__c> challengelist=database.query(soqlQuery);
        system.debug(challengelist);
        return challengelist;
        
    }
    
    //this method is used to perform insert,update operation on challenge__c object and if Record is already upto date then it will return Challenge Already Marked as Completed message.
    @AuraEnabled
    public static string challengecompleted(String challangeName)
    {
        
        system.debug(challangeName);
        id userid,challangeid;
        boolean completestatus;
        userid=UserInfo.getUserId();
        system.debug(userid);
        
        string soqlQuery ='select id from challenge__c where name= '+'\''+ challangeName +'\'';
         list<challenge__c> challengelist=database.query(soqlQuery);
        for(challenge__c chall:challengelist)
        {
           
            challangeid=chall.Id;
        }
      
        string soqlQuery1 ='select name,id,Challenge__c,Completed__c from completion__c where Challenge__c= '+'\''+ challangeid+'\'';//+' and Completed__c= '+'\''+ True +'\'';
        list<completion__c> complitionlistcheck=database.query(soqlQuery1);
        integer size=complitionlistcheck.size();
        
        for(completion__c comp:complitionlistcheck)
        {
           
            completestatus=comp.Completed__c;
        }
        
        if(size>=1 && completestatus==True)
        {
            system.debug('Challenge Already Marked as Completed');
            return 'Challenge Already Marked as Completed';
        }
        else if(size>=1 && completestatus==False)
        {
       
            completion__c completionToUpdate;
            
            completionToUpdate = [SELECT id,Completed__c FROM completion__c WHERE Completed__c=False AND Challenge__c=:challangeid LIMIT 1];
    
    					completionToUpdate.Completed__c = True;
  
   			update completionToUpdate;
            system.debug('Record Updated Successfully');
            return 'Record Updated Successfully';
            
           
        }
        
        
        try
        {
        Completion__c complete=new completion__c(Challenge__c=challangeid,Completed__c=True,User__c=userid);
        insert complete;
        return 'Compelete Status Updated Successfully';
        }
        catch(exception e)
        {
            return 'There is Some Error in Updating Status';
        }
    }
}