force-app/main/default/objects/Challenge__c/Challenge__c.object-meta.xml
<CustomObject>
    <description>The specific task that a User would need to complete to get credit to be used for their overall score.</description>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Challenge__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the tech the challenge is about.</description>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>Challenges</relationshipLabel>
    <relationshipName>Challenges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Challenge__c/fields/Sub_Tech__c.field-meta.xml
<CustomField>
    <fullName>Sub_Tech__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The sub tech in which this specific challenge will be associated to.</description>
    <label>Sub Tech</label>
    <referenceTo>Sub_Tech__c</referenceTo>
    <relationshipLabel>Challenges</relationshipLabel>
    <relationshipName>Challenges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Completion__c/Completion__c.object-meta.xml
<CustomObject>
    <description>The Junction object for Challenges and User that is used to keep a record of completed challenges. Records of this object should be created when User is assigned a Stack.</description>
    <label>Completion</label>
    <nameField>
        <displayFormat>Comp-{0000000}</displayFormat>
        <label>Completion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Completion__c/fields/Challenge__c.field-meta.xml
<CustomField>
    <fullName>Challenge__c</fullName>
    <label>Challenge</label>
    <referenceTo>Challenge__c</referenceTo>
    <relationshipLabel>Completions</relationshipLabel>
    <relationshipName>Completions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Completion__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Challenge completed by the user?</description>
    <label>Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Completion__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Completions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Tech__c/Primary_Tech__c.object-meta.xml
<CustomObject>
    <description>The overview tech  that can be associated to multiple stacks that will multiple sub techs which will inform which challenges belong</description>
    <label>Primary Tech</label>
    <nameField>
        <label>Primary Tech Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Techs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stack_Tech__c/Stack_Tech__c.object-meta.xml
<CustomObject>
    <description>The Primary Tech to Stack assignment junction object.</description>
    <label>Stack Tech</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Stack Tech Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stack Techs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stack_Tech__c/fields/Primary_Tech__c.field-meta.xml
<CustomField>
    <fullName>Primary_Tech__c</fullName>
    <label>Primary Tech</label>
    <referenceTo>Primary_Tech__c</referenceTo>
    <relationshipLabel>Stack Techs</relationshipLabel>
    <relationshipName>Stack_Techs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stack_Tech__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>Stack Techs</relationshipLabel>
    <relationshipName>Stack_Techs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sub_Tech__c/Sub_Tech__c.object-meta.xml
<CustomObject>
    <description>The specific tech in which the challenges would be made to cover.</description>
    <label>Sub Tech</label>
    <nameField>
        <label>Sub Tech Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Techs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Tech__c/fields/Primary_Tech__c.field-meta.xml
<CustomField>
    <fullName>Primary_Tech__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Tech</label>
    <referenceTo>Primary_Tech__c</referenceTo>
    <relationshipLabel>Sub Techs</relationshipLabel>
    <relationshipName>Sub_Techs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Stack__c/User_Stack__c.object-meta.xml
<CustomObject>
    <description>The Stack to User assignment Object.</description>
    <label>User Stack</label>
    <nameField>
        <displayFormat>UseS-{000000}</displayFormat>
        <label>User Stack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stack__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <referenceTo>Stack__c</referenceTo>
    <relationshipLabel>User Stacks</relationshipLabel>
    <relationshipName>User_Stacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Stack__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stacks</relationshipName>
    <type>Lookup</type>
</CustomField>

interview-board-administration/main/default/classes/UserStackTriggerHelper.cls
public class UserStackTriggerHelper {
    public static void createComplete(List<User_Stack__c> useStacks){
        List<Id> userIDs = new List<Id>();
        List<Id> stackIDs = new List<Id>();
        for(User_Stack__c us: useStacks){
            stackIDs.add(us.Stack__c);
            userIDs.add(us.User__c);
        }
        List<Stack_Tech__c> sTechs = [SELECT Primary_Tech__c FROM Stack_Tech__c WHERE Stack__c IN :stackIDs];
        List<Id> primeTechIDs = new List<Id>();
        for(Stack_Tech__c st: sTechs){
            if(!(primeTechIDs.contains(st.Primary_Tech__c))){
            	primeTechIDs.add(st.Primary_Tech__c);
            }
        }
        List<Sub_Tech__c> subTechs = [SELECT Id FROM Sub_Tech__c WHERE Primary_Tech__c IN :primeTechIDs];
        List<Id> subTechIDs = new List<Id>();
        for(Sub_Tech__c subt: subTechs){
            subTechIDs.add(subt.id);
        }
        List<Challenge__c> challs = [SELECT Id FROM Challenge__c WHERE Sub_Tech__c IN :subTechIDs];
        List<Id> challIDs = new List<Id>();
        for(Challenge__c chall: challs){
            challIDs.add(chall.id);
        }
        List<Completion__c> comps =[SELECT User__c, Challenge__c FROM Completion__c WHERE User__c IN :userIDs AND Challenge__c IN :challIDs];
        Set<Completion__c> newComps = new Set<Completion__c>();
        for(Id userId: userIDs){
            for(Id challID: challIDs){
                Completion__c comp = new Completion__c();
                comp.Challenge__c = challID;
                comp.User__c = userId;
                comp.Completed__c = false;
                newComps.add(comp);
            }
        }
        for(Completion__c newComp: newComps){
            for(Completion__c oldComp: comps){
                if(newComp.Challenge__c == oldComp.Challenge__c && newComp.User__c == oldComp.User__c){
                    newComps.remove(newComp);
                }
            }
        }
        //Needs to be a List to insert in to Database
        List<Completion__c> newCompsL = new List<Completion__c>(newComps);
        insert newCompsL;
    }
}