force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <formula>Participating_Client__r.Participant__r.FirstName + &quot; &quot; + Participating_Client__r.Participant__r.LastName+ &quot;, &quot; + &quot;Company: &quot; + Participating_Client__r.Participant__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <label>Meeting Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Mock</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Schedule</fullName>
                <isActive>false</isActive>
                <label>On Schedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <label>Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssociateMockInterviewsController.cls
public class AssociateMockInterviewsController {

    @auraenabled
    public static Meeting__c[] GetUpcomingMeetings()
    {//returns all future meetings the logged in associate is a participant of that arent mock interviews
 
       
         ID userId = System.UserInfo.getUserId();
         User userContactId = [Select Contact.id FROM USER WHERE ID = :userId] ;
        Id MockId = Schema.SObjectType.Meeting__c.getRecordTypeInfosByName().get('Mock Interview').getRecordTypeId();
                
               return  [SELECT Id, Name, Client_Name__c , Meeting_status__c , Scheduled__c , location__c
                                                    FROM Meeting__c
                                                    WHERE Id IN (SELECT Meeting__c 
                                                                 FROM Meeting_Participant__c 
                                                                 WHERE Participant__c  = :userContactId.ContactId
                                                                 ) AND Scheduled__c > : System.now() AND RecordTypeId != : MockId ];
    }

    @auraEnabled
     public static Meeting__c[]  GetFutureMockInterviews()
     {//returns all upcoming mock interviews
         
             
         ID userId = System.UserInfo.getUserId();
         User userContactId = [Select Contact.id FROM USER WHERE ID = :userId] ;
       Id MockId = Schema.SObjectType.Meeting__c.getRecordTypeInfosByName().get('Mock Interview').getRecordTypeId();
                
               return  [SELECT Id, Name, Notes__c
                                                    FROM Meeting__c
                                                    WHERE Id IN (SELECT Meeting__c 
                                                                 FROM Meeting_Participant__c 
                                                                 WHERE Participant__c  = :userContactId.ContactId
                                                                 ) AND Scheduled__c > : System.now() AND RecordTypeId = : MockId ];
         
         
     }
    
    
}