force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <label>Meeting Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Mock</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Schedule</fullName>
                <isActive>false</isActive>
                <label>On Schedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MockInterviewsListControllerTest.cls
@isTest
public class MockInterviewsListControllerTest {
    
    @testSetup
    static void makeUser(){
        
        Account testAcc = new Account();
        testAcc.name = 'test company';
        Database.SaveResult savedAccount = Database.insert(testAcc);
        Id accID = savedAccount.getId();
        
        
        Contact con = new Contact(lastname = 'stuff', AccountId = accId);
        Database.SaveResult savedContact = Database.insert(con);
        

        
        Id contId = savedContact.getId();
        Profile prof = [SELECT id FROM Profile WHERE Name = 'Associate'];
        
        User u = new User(firstName = 'test1', lastName ='stuff', profileId = prof.id, 
                          username = 'test@test.com', email = 'test@test.com', ContactId = contId,
                          alias= 'Test', TimeZoneSidKey='America/New_York', LocaleSidKey='en_US',
                          EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', IsActive = true);
        insert u;
        
        
        
    }
    
    @isTest
    public static void MockInterviewsListControllerTest() {
        User testUser = [SELECT id FROM User WHERE lastName='stuff']; 
        
        Contact conta = [SELECT id FROM Contact WHERE lastname='stuff'];
        
        Id recordTypeId = Schema.SObjectType.Meeting__c.getRecordTypeInfosByName().get('Mock Interview').getRecordTypeId();
            
        Meeting__c newMeet = new Meeting__c(Name = 'TestMeeting', Meeting_Status__c = 'Mock', RecordTypeId=recordTypeId);
        
        
        Database.SaveResult savedMeeting = Database.insert(newMeet);
        
        Id meetId = savedMeeting.getId();
        
        
        Meeting_Participant__c mP = new Meeting_Participant__c(Name='LOLOLOL', Participant__c=conta.Id, Meeting__c= meetId);
        
        insert mP;
        
        System.runAs(testUser) {
            
            
            
            List<Meeting__c> returnedList = MockInterviewsListController.getInterviews();

            
            
            system.assertEquals(1, returnedList.size());
            
            
        }
    }
    
}