force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Interview_Question__c/Interview_Question__c.object-meta.xml
<CustomObject>
    <label>Interview Question</label>
    <nameField>
        <label>Interview Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Question__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview_Question__c/fields/Meeting_md__c.field-meta.xml
<CustomField>
    <fullName>Meeting_md__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Interview Questions (Meeting)</relationshipLabel>
    <relationshipName>Interview_Questions1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interview_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Interview Questions</relationshipLabel>
    <relationshipName>Interview_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <label>Meeting Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Mock</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>On Schedule</fullName>
                <isActive>false</isActive>
                <label>On Schedule</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <label>Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <label>Meeting Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssociateMeetingsControllerTest.cls
@isTest(seeAllData=True)
public class AssociateMeetingsControllerTest {    
    @isTest
    static void testAsCommunityUser(){
        //Create Test Community User with contact associated with it. 
        
        Contact con = [SELECT Id, Name FROM Contact WHERE Name = 'Arthur Song'];
        Profile prof = [select id from profile where name = 'Associate'];
        User u = new User(firstName = 'test1', lastName ='test2', profileId = prof.id, 
                          username = 'test@test.com', email = 'test@test.com', ContactId = con.Id,
                          alias= 'Test', TimeZoneSidKey='America/New_York', LocaleSidKey='en_US',
                          EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', IsActive = true);
        insert u;
        
        System.runAs(u) {
            //Get Test User's Id and ContactId
            
            ID userId = System.UserInfo.getUserId();
            User userContactId = [Select Contact.Id FROM USER WHERE ID = :userId];
            //Create Meetings with Mock Interview and Non-Mock Interview Record Types
            
            Meeting__c[] meets = new Meeting__c[]{};
                Integer x = 3;
            For(Integer i=0; i < x; i++){
                meets.add(new Meeting__c(Name = 'Test Non-Mock Interview ' + (i+1), RecordTypeId = '0123h0000006O1SAAU',Scheduled__c = System.today()+ 3));
                meets.add(new Meeting__c(Name = 'Test Mock Interview ' + (i+1), RecordTypeId ='0123h0000006OXmAAM'));
                meets.add(new Meeting__c(Name = 'Test Past Interview Batch ' + (i+1), RecordTypeId = '0123h0000006O1VAAU', Scheduled__c = System.today() -3,Meeting_Status__c = 'Completed'));
                meets.add(new Meeting__c(Name = 'Test Past Interview 1-1 ' + (i+1), RecordTypeId = '0123h0000006O1UAAU', Scheduled__c = System.today() -3,Meeting_Status__c = 'Completed'));
            }
            insert meets;
            //For Each Meeting Just Inserted, Add Meeting Participants
            
            List<Meeting_Participant__c> persons = new List<Meeting_Participant__c>();
            for (Integer j=0;j<x*4;j++) {
                Meeting__c meet = meets[j];
                
                for (Integer k=0;k<1;k++) {
                    persons.add(new Meeting_Participant__c(Name=meet.Name + ' Participant ' + (k+1),
                                                           Meeting__c = meet.Id,
                                                           Participant__c = userContactId.ContactId
                                                          ));
                }
            }
            insert persons;
            //Create Interview Questions for a Test Meeting
            Question__c[] quests = new Question__c[]{};
                For(Integer i=0; i < x; i++){
                    quests.add(new Question__c(Name = 'Test'));
                }
            insert quests; 
            List<Interview_Question__c> questions = new List<Interview_Question__c>();
            Meeting__c testMeeting = meets[0];
            System.debug(testMeeting);
            
            for (Integer k=0;k<x;k++) {
                Question__c quest = quests[k];
                questions.add(new Interview_Question__c(Meeting_md__c = testMeeting.Id,
                                                        Question__c = quest.Id));
            }
            
            insert questions;
            Meeting__c meet = [SELECT Id FROM Meeting__c WHERE Name = 'Test Non-Mock Interview 1'];
            String meetingid = meet.Id;
            //Start Test
            
            Test.startTest();
            Meeting__c[] meetings = AssociateMeetingController.GetUpcomingMeetings();
            Meeting__c[] mockInterviews =  AssociateMeetingController.GetFutureMockInterviews();
            Meeting__c[] pastInterviews =  AssociateMeetingController.GetPastInterviews();
            Interview_Question__c[] interviewQuestions = AssociateMeetingController.GetInterviewQuestions(meetingid);
            
            //Stop Test
            
            Test.stopTest();
            //Check If the Controller Performs As Expected
            
            System.assertEquals(3, meetings.size());
            System.assertEquals(3, mockInterviews.size());
            System.assertEquals(6, pastInterviews.size());
            System.assertEquals(3, interviewQuestions.size());
        }
    }
}