force-app/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Question__c/fields/Stack__c.field-meta.xml
<CustomField>
    <fullName>Stack__c</fullName>
    <label>Stack</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>.NET</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Pop Culture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <description>The specific task that a User would need to complete to get credit to be used for their overall score.</description>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <label>Date and Time</label>
    <type>DateTime</type>
</CustomField>

package/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>sfqz__Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sfqz__Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stack__c/Stack__c.object-meta.xml
<CustomObject>
    <description>Stacks are objects that can be assigned to users to connect them with challenges to be completed based on the subject.</description>
    <label>Stack</label>
    <nameField>
        <label>Stack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SessionController.cls
public with sharing class SessionController {
    @AuraEnabled(cacheable=true)
    
    //return the matching records based on SOQL if the user doesn't enter a search term 
    public static List<Quiz_Session__c> getSessions(String searchKey) {
        if (String.isBlank(searchKey)) {
         
            return [SELECT Id,Date_and_Time__c, Phase__c, Current_Question__r.Id, Current_Question__r.Stack__c  FROM Quiz_Session__c WHERE Date_and_Time__c = TODAY ORDER BY Date_and_Time__c];

    }
    else {
        //return the matching records based on SOQL and the user's search
        String key = '%' + searchKey + '%';
        return [SELECT Id, Date_and_Time__c,Phase__c, Current_Question__r.Id, Current_Question__r.Stack__c  FROM Quiz_Session__c WHERE Phase__c LIKE :key AND Date_and_Time__c = TODAY ORDER BY Date_and_Time__c];
    } 
}
@AuraEnabled(cacheable=true)

//if no records return, notify the user
public static Quiz_Session__c getSession(Id sessionID) {
    List<Quiz_Session__c> sessions = [SELECT Id,Phase__c
    FROM Quiz_Session__c WHERE Date_and_Time__c = TODAY];
  if (sessions.size() != 1) {
    throw new AuraHandledException('Could not find session');
  }
  return sessions[0];
}

}